### ISSUE TITLE
Medium Size is wrong

### ISSUE THREAD

**Issue by wamry** [aminebenkeroum/toggle-switch-react-native#16]
This should be the setting for medium toggle button, not the current one 

      `width: 65, padding: 14, circleWidth: 23, circleHeight: 23, translateX: 30,`

**Comment by aminebenkeroum** [comment]
@wamry  I fixed the styling, tell me if it suits your needs.

**Comment by wamry** [comment]
This still didn't fix the problem, the problem is that medium and small are too close in this, they both look small.
Here's my styling for medium:
`{width: 60, padding: 14.5, circleWidth: 24, circleHeight: 24, translateX: 30 }
`

Also, in my fork, I needed to have the translateX be -1 instead of 0
`const toValue = isOn
      ? this.dimensions.width - this.dimensions.translateX
      : -1;`

Not sure if this translate will work for the other sizes or not.
