### ISSUE TITLE
Use `useNativeDriver` for the animations?

### ISSUE THREAD

**Issue by dotintechno** [aminebenkeroum/toggle-switch-react-native#25]

**Comment by aminebenkeroum** [comment]
Great idea! I will be implementing it soon.

**Comment by maximilize** [comment]
The missing property `useNativeDriver`is now causing a warning in react-native.

```
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`
```

**Comment by jstarmx** [comment]
I see this has been fixed a few months ago in the codebase, any chance of a new release so we can use it please? 🙂

**Comment by Northshoot** [comment]
Any update on this? Can it be released?

**Comment by mike-niemand** [comment]
Thanks for this component. 

I'm still getting this error on 2.2.0?

**Comment by BrijeshPandya-j2** [comment]
I am still getting this warning  **Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`** after using latest version **2.2.0** and React Native version is **0.62.2**

**Comment by BrijeshPandya-j2** [comment]
I am still getting this warning **Animated: useNativeDriver was not specified. This is a required option and must be explicitly set to true or false** I am using latest version of this package which is **2.2.0** and React Native version is **0.62.2**

**Comment by jstarmx** [comment]
Yes I see the fix had been removed when release 2.2.0 was created, and has since been reinstated, if you could make an updated release please when you can?

<img width="813" alt="Screenshot 2020-09-09 at 15 57 57" src="https://user-images.githubusercontent.com/12033907/92615693-4a6ed000-f2b5-11ea-9bd4-c5c46bd3b9aa.png">
